import React, { useState } from 'react'
import { useParams } from 'react-router-dom'
import InPageNavigation from './InPageNavigation'

export default function MatchDetail() {

    let team1={
  "player": [
    {
      "player": [
        {
          "id": "11813",
          "name": "Ruturaj Gaikwad",
          "captain": true,
          "role": "Batsman",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 333874,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "11177",
          "name": "Rachin Ravindra",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351609,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "1447",
          "name": "Ajinkya Rahane",
          "captain": false,
          "role": "Batsman",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 332892,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "10713",
          "name": "Daryl Mitchell",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351601,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "587",
          "name": "Ravindra Jadeja",
          "captain": false,
          "role": "Bowling Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 352483,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "14700",
          "name": "Sameer Rizvi",
          "captain": false,
          "role": "Batsman",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "265",
          "name": "MS Dhoni",
          "captain": false,
          "role": "WK-Batsman",
          "keeper": true,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 170677,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "7836",
          "name": "Deepak Chahar",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 226392,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "18504",
          "name": "Maheesh Theekshana",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351936,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "9863",
          "name": "Mustafizur Rahman",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351909,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "MOUT",
          "isoverseas": true
        },
        {
          "id": "11307",
          "name": "Tushar Deshpande",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 190903,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "playing XI"
    },
    {
      "player": [
        {
          "id": "8683",
          "name": "Shardul Thakur",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 352487,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "11195",
          "name": "Shivam Dube",
          "captain": false,
          "role": "Bowling Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 183291,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "MIN",
          "isoverseas": false
        },
        {
          "id": "22571",
          "name": "Shaik Rasheed",
          "captain": false,
          "role": "Batsman",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "22576",
          "name": "Nishant Sindhu",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "6692",
          "name": "Moeen Ali",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351579,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        }
      ],
      "category": "substitutes"
    },
    {
      "player": [
        {
          "id": "10100",
          "name": "Mitchell Santner",
          "captain": false,
          "role": "Bowling Allrounder",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351608,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "11777",
          "name": "Ajay Jadav Mandal",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "12805",
          "name": "Prashant Solanki",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "13184",
          "name": "Mukesh Choudhary",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "14163",
          "name": "Simarjeet Singh",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "14599",
          "name": "RS Hangargekar",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 226294,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "51767",
          "name": "Aravelly Avanish",
          "captain": false,
          "role": "WK-Batsman",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "bench"
    },
    {
      "player": [
        {
          "id": "49",
          "name": "Stephen Fleming",
          "captain": false,
          "role": "Head coach",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 151497,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "4772",
          "name": "Michael Hussey",
          "captain": false,
          "role": "Batting coach",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 180290,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "242",
          "name": "Dwayne Bravo",
          "captain": false,
          "role": "Bowling coach",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 171033,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "42611",
          "name": "Rajiv Kumar",
          "captain": false,
          "role": "Batting and Fielding Coach",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "5487",
          "name": "Eric Simons",
          "captain": false,
          "role": "Bowling Consultant",
          "keeper": false,
          "teamname": "CSK",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 157813,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "support staff"
    }
  ]
}
 
    let team2={
  "player": [
    {
      "player": [
        {
          "id": "7825",
          "name": "Faf du Plessis",
          "captain": true,
          "role": "Batsman",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 170639,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "1413",
          "name": "Virat Kohli",
          "captain": false,
          "role": "Batsman",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 332891,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "10636",
          "name": "Rajat Patidar",
          "captain": false,
          "role": "Batsman",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 234983,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "7662",
          "name": "Glenn Maxwell",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 352454,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "12225",
          "name": "Cameron Green",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 352451,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "145",
          "name": "Dinesh Karthik",
          "captain": false,
          "role": "WK-Batsman",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 244969,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "MOUT",
          "isoverseas": false
        },
        {
          "id": "13135",
          "name": "Anuj Rawat",
          "captain": false,
          "role": "WK-Batsman",
          "keeper": true,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 226472,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "1844",
          "name": "Karn Sharma",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 226391,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "11220",
          "name": "Alzarri Joseph",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 244661,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": true
        },
        {
          "id": "10953",
          "name": "Mayank Dagar",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "10808",
          "name": "Mohammed Siraj",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 352491,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "playing XI"
    },
    {
      "player": [
        {
          "id": "14172",
          "name": "Yash Dayal",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "MIN",
          "isoverseas": false
        },
        {
          "id": "14726",
          "name": "Akash Deep",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "12669",
          "name": "Suyash Prabhudessai",
          "captain": false,
          "role": "Batsman",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "10238",
          "name": "Swapnil Singh",
          "captain": false,
          "role": "Bowling Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "10486",
          "name": "Vijaykumar Vyshak",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "substitutes"
    },
    {
      "player": [
        {
          "id": "10954",
          "name": "Mahipal Lomror",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 226541,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "8349",
          "name": "Reece Topley",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351852,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "9522",
          "name": "Tom Curran",
          "captain": false,
          "role": "Bowling Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 170967,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "10692",
          "name": "Lockie Ferguson",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 351814,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "12258",
          "name": "Will Jacks",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "13962",
          "name": "Manoj Bhandage",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "21686",
          "name": "Saurav Chauhan",
          "captain": false,
          "role": "Batting Allrounder",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "32786",
          "name": "Rajan Kumar",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "36482",
          "name": "Himanshu Sharma",
          "captain": false,
          "role": "Bowler",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "bench"
    },
    {
      "player": [
        {
          "id": "3406",
          "name": "Andy Flower",
          "captain": false,
          "role": "Head Coach",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 153350,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "3942",
          "name": "Sridharan Sriram",
          "captain": false,
          "role": "Batting Coach",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "42663",
          "name": "Adam Griffith",
          "captain": false,
          "role": "Bowling Coach",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        },
        {
          "id": "8899",
          "name": "Malolan Rangarajan",
          "captain": false,
          "role": "Head of Scouting and Fielding Coach",
          "keeper": false,
          "teamname": "RCB",
          "isheader": false,
          "imageId": 0,
          "battingStyle": "",
          "bowlingStyle": "",
          "faceimageid": 182026,
          "countryimageid": 0,
          "playingxichange": "",
          "inmatchchange": "",
          "isoverseas": false
        }
      ],
      "category": "support staff"
    }
  ]
    }

    const[data,setData]=useState([])

    let {id}=useParams()
    console.log(id);
    
  return (
    <div className='w-screen flex justify-center items-center flex-col '>
      <h1 className='sm:w-1/2 w-4/5 sm:text-5xl text-4xl p-3 font-bold'> Balaji's Match </h1>
            <InPageNavigation teams={[team1.player[0].player[0].teamname,team2.player[0].player[0].teamname]}>

                    {
                        team1.player[0].player.map(data=>
                            <div key={data.id} 
                                className='border-2 mb-1 p-2'>
                                <h1 className='text-xl font-sans'>{data.name}</h1>
                                <p className='text-gray-500'>{data.role}</p>
                            </div>
                        )
                    }

                    {
                        team2.player[0].player.map(data=>
                            <div key={data.id}
                                className='border-2 mb-1 p-2'>
                                <h1 className='text-xl font-sans'>{data.name}</h1>
                                <p className='text-gray-500'>{data.role}</p>
                            </div>
                        )
                    }

                
            </InPageNavigation>
    </div>
  )
}
